@startuml alert_rec09_ordersign
!theme carbon-gray
<style>
activityDiagram {
 FontColor white
 arrow {
  FontColor: Black
 }
 note {
  FontColor: Black
  BackgroundColor: #fafad2
 }
}
</style>
#b06f19:Alert;<<output>>
note right
**SUMMARY**: Before Ordering Opioids, Review PDMP Data

**DETAILS**:
Review PDMP data for this patient before completing 
opioid order.

For guidance about utilizing PDMP information to 
improve patient safety, see 
[[https://www.cdc.gov/mmwr/volumes/71/rr/rr7103a1.htm#Recommendation9 Recommendation 9 of the 2022 CDC Clinical Practice Guideline]].
end note
split
#c05046:Access Data - 
Launch app to review
PDMP data;<<input>>
kill
split again
#c05046:Document - 
PDMP data reviewed, 
Snooze 3 months*;<<input>>
kill
split again
#c05046:Snooze* - 
N/A see comment, 
Snooze 3 months*;<<input>>
kill
end split
caption ~*Snooze duration referenced in the alert response is an example and is intended to be patient specific.
@enduml