@startuml flow_rec12_patientview
!theme carbon-gray
skinparam hyperlinkColor white
<style>
activityDiagram {
 FontColor white
 RoundCorner 50
 arrow {
  FontColor: Black
 }
 diamond {
  BackgroundColor #306516
 }
}
</style>
title Recommendation 12 Patient View Flow Diagram
#1C2ED5:Patient View; 
#fc914d:if ([[subroutines.html#cdc-2022-general-inclusion-criteria CDC 2022 guideline\n   general inclusion\n      criteria met?]]) then (no)
(yes) elseif (  Diagnosis of opioid use\n disorder in past 90 days?) then (no)
(yes) elseif (      No active order \n  for buprenorphine or \nmethadone medications?) then (no) 
else (yes) 
#b06f19:[[user-interaction-alerts.html#recommendation-12-alert Alert]];<<output>>
kill
endif
#BC2C73:No Alert*;
caption ~*When no alert is warranted by the guidance, the user should not experience any interruption.
@enduml