@startuml legend_user_interaction
!theme carbon-gray
skinparam LegendFontSize 10
legend left
|<#b06f19>|  User Interaction |
|<#c05046>|  EHR Configured Alert Response Options Examples |
endlegend
@enduml