@startuml subroutine_opioid_benzodiazepine_cns_order
!theme carbon-gray
skinparam ActivityBackgroundColor #306516
<style>
activityDiagram {
 FontColor white
 RoundCorner 50
 arrow {
  FontColor: Black
 }
 diamond {
  BackgroundColor #306516
 }
}
</style>
title Order for Opioid Analgesic, Benzodiazepine or CNS Depressant Subroutine
start
fork
:      Order for opioid \nanalgesic with ambulatory \n      misuse potential?;
fork again
: Order for benzodiazepine?;
fork again
: Order for central nervous \n     system depressant?;
end merge
if (Any answer is yes?) then (yes)
#BC2C73:Return Yes;
kill
else (no)
#BC2C73:Return No;
kill
@enduml